// examples/vue-min/src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { createClient } from '@nura-js/client';
import { createDispatcher, createIntent } from '@nura-js/core';

type GreetingIntent = ReturnType<typeof createGreetingIntent>;

const dispatcher = createDispatcher({
  registry: {
    'hello.intent': { required: ['name'] },
  },
});

dispatcher.register('hello.intent', {
  perform: ({ payload }) => `Nura whispers back: hello ${payload.name}!`,
});

const client = createClient<GreetingIntent, string>({ dispatcher });

function createGreetingIntent(name: string) {
  return createIntent('hello.intent', { name });
}

const name = ref('traveler');
const intent = computed(() => createGreetingIntent(name.value));

const isPending = ref(false);
const result = ref('');
const error = ref('');

const onClick = async () => {
  isPending.value = true;
  error.value = '';
  try {
    result.value = await client.dispatch(intent.value);
  } catch (err) {
    error.value = String(err);
  } finally {
    isPending.value = false;
  }
};
</script>

<template>
  <main class="wrapper">
    <h1>Nura Vue minimal</h1>
    <label>
      <span>Name</span>
      <input v-model="name" />
    </label>
    <button type="button" :disabled="isPending" @click="onClick">
      {{ isPending ? 'Breathing…' : 'Send intent' }}
    </button>
    <p v-if="result">Agent replied: {{ result }}</p>
    <p v-if="error" class="error">Error: {{ error }}</p>
  </main>
</template>

<style scoped>
.wrapper {
  min-height: 100vh;
  display: grid;
  gap: 1rem;
  place-content: center;
  font-family: system-ui;
}

button {
  font-size: 1.1rem;
  padding: 0.75rem 1.5rem;
}

.error {
  color: tomato;
}
</style>

// packages/create-nura/src/templates/react/src/App.tsx
import { useMemo } from 'react';
import { createClient } from '@nura-js/client';
import { createDispatcher, createIntent } from '@nura-js/core';

const dispatcher = createDispatcher({
  registry: {
    'hello.intent': { required: ['name'] },
  },
});

dispatcher.register('hello.intent', {
  perform: ({ payload }) => `Nura breathes back: hello ${payload.name}!`,
});

const client = createClient({ dispatcher });

export default function App() {
  const intent = useMemo(() => createIntent('hello.intent', { name: 'traveler' }), []);

  const handleClick = async () => {
    const result = await client.dispatch(intent);
    alert(result);
  };

  return (
    <main style={{ fontFamily: 'system-ui', padding: '4rem', textAlign: 'center' }}>
      <h1>Nura says hi</h1>
      <p>Press the button to send an intent to your local agent.</p>
      <button onClick={handleClick} style={{ fontSize: '1.25rem', padding: '0.75rem 1.5rem' }}>
        Send intent
      </button>
    </main>
  );
}
